# Site Settings
# You can change the settings below in order to customize your website.
name: "JekyllExample.com"
title: "JekyllExample.com - A sample Jekyll Example website! "
description: "A sample website built on the Jekyll platform designed to make it easy for you to get a website of your own up and running."
logo: 'assets/Logo.png'
favicon: '/assets/favicon.ico'
baseurl: ""
google_analytics: 'G-ZKHV3G3SN8' # configured for Google Analytics 4 MEASUREMENT ID
# disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
url: 'https://www.jekyllexample.com'

templatemessage: 'Forked from <a href="https://www.chrishammond.com/">Chris Hammond</a>''s <a href="https://www.jekyllexample.com">JekyllExample.com</a>.'

# Authors
authors:
  chris:
    name: Chris Hammond
    display_name: Chris Hammond
    first_name: Chris
    last_name: Hammond
    gravatar: bff097b7cc348bebce39ee1c7694d125
    email: jekyll@christoc.com
    web: https://www.chrishammond.com
    twitter: https://twitter.com/christoc
    description: "Creator of JekyllExample.com. Read more at <a href=\"https://www.chrishammond.com\">Chris Hammond</a>" 

# Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
      
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

#any defaults we want to set, the first one sets the default author for all posts
defaults:
  - scope:
      path: ""  # An empty string here means all files
      type: "posts"
    values:
      author: "chris"

# exclude:
#  - /assets/images/*
